FROM arm64v8/python:3.10-slim

COPY manifest.json /bosdyn/etc/spot_payload.json

COPY requirements.txt ./
# RUN pip install --no-cache-dir -r requirements.txt
RUN python3 -m pip install pip==21.3.1 setuptools==59.6.0 wheel==0.37.1 && \
    python3 -m pip install -r requirements.txt --find-links .

COPY easy_walk.py /app/
WORKDIR /app

ENTRYPOINT ["python3", "/app/easy_walk.py"]